version: '3'

services:
  bitpoll:
    build: .
    container_name: bitpoll
    restart: always
    ports:
      - 8000:8000
    networks:
      - host_net
    volumes:
      - ${PWD}/:/app
      - /var/run/mysqld/:/var/run/mysqld/:rw

volumes:
  bitpoll:
    driver_opts:
      type: "none"
      o: "bind"
      device: "$PWD/"

networks:
  host_net:
    driver: bridge
